const graph = {
  MainEntrance: ["AcademicArea", "GirlsHostels", "Student2WParking"],
  AcademicArea: ["MainEntrance", "GirlsHostels", "AuditoriumAdmin", "LibraryMBA", "CivilBlock"],
  AuditoriumAdmin: ["AcademicArea", "PhysicsDepartment", "Bank", "AdministrativeBlock", "CSEBlock", "ISEBlock", "FacultyParking"],
  AdministrativeBlock: ["AuditoriumAdmin", "FacultyParking"],
  CSEBlock: ["AuditoriumAdmin", "ISEBlock"],
  ISEBlock: ["AuditoriumAdmin", "CSEBlock", "ECEBlock", "EEEBlock"],
  ECEBlock: ["ISEBlock", "EEEBlock"],
  EEEBlock: ["ISEBlock", "ECEBlock"],
  PhysicsDepartment: ["AuditoriumAdmin", "CivilBlock", "ChemistryDepartment", "CanteenSIC"],
  ChemistryDepartment: ["PhysicsDepartment"],
  LibraryMBA: ["AcademicArea", "IndoorSports", "PlacementOffice", "MBADepartment"],
  CivilBlock: ["AcademicArea", "PhysicsDepartment", "MechanicalBlock"],
  MechanicalBlock: ["CivilBlock", "Temple", "CanteenSIC", "AIMLBlock", "Karavali", "TransportationSection"],
  AIMLBlock: ["MechanicalBlock"],
  Temple: ["MechanicalBlock", "BoysHostels"],
  Bank: ["AuditoriumAdmin", "PostOffice"],
  CanteenSIC: ["PhysicsDepartment", "MechanicalBlock", "BoysHostels"],
  BoysHostels: ["Temple", "CanteenSIC", "Mess"],
  GirlsHostels: ["MainEntrance", "AcademicArea", "Student2WParking"],
  Mess: ["BoysHostels", "Playground"],
  IndoorSports: ["LibraryMBA", "Playground"],
  Playground: ["IndoorSports", "Mess"],
  PlacementOffice: ["LibraryMBA"],
  MBADepartment: ["LibraryMBA"],
  Karavali: ["MechanicalBlock", "XeroxShop"],
  XeroxShop: ["Karavali"],
  Student2WParking: ["GirlsHostels", "MainEntrance"],
  FacultyParking: ["AdministrativeBlock", "AuditoriumAdmin"],
  PostOffice: ["Bank"],
  TransportationSection: ["MechanicalBlock"],
};

export default graph;
